blank_issues_enabled: false
contact_links:
  - name: P2 Forum Community Support
    url: https://forums.parallax.com/discussion/174283/using-a-raspberry-pi-as-an-iot-gateway-for-our-p2-projects#latest
    about: Discuss the P2 IoT Gateway here.

