#!/bin/bash

SRC_SPIN_DIR=/Users/stephen/Dropbox/PropV2-Shared/Projects/P2-VL53L5CX-TOF-DrvrSW

DST_SPIN_DIR="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Propeller2/P2-VL53L5CX-time-of-flight/P2-VL53L5CX-time-of-flight-driver/src"
DST_SPIN_DIR2="/Users/stephen/Projects/Projects-ExtGit/IronSheepProductionsLLC/Projects Propeller/P2-VL53L5CX-time-of-flight/P2-VL53L5CX-time-of-flight-driver/src"

if [ ! -d "${DST_SPIN_DIR}" ]; then
    DST_SPIN_DIR="${DST_SPIN_DIR2}"
fi

(set -x;cp -p "${SRC_SPIN_DIR}"/*.spin2 "${DST_SPIN_DIR}")
